import Head from 'next/head';
import Image from 'next/image';
import BubleMenuComponent from '../components/buble_menu_component/BubleMenuComponent';
import CentralHeroComponent from '../components/central_hero_component/CentralHeroComponent';
import ParticlesComponent from '../components/particles/Particles';
import StickyContactComponent from '../components/sticky_contact_component/StickyContactComponent';
import TextComponent from '../components/text_component/TextComponent';
export default function Home() {
  return (
    <div className="h-screen center-verticaly">
      <Head>
        <title>Pablo Salgado Desarrollador Fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" h-screen grid grid-cols-3 items-center w-full">
        <div className="menus z-10 center-verticaly">
          <h3 className="text-2xl text-white m-8">Mi Contenido</h3>
          <BubleMenuComponent></BubleMenuComponent>
        </div>
        <div className="center-verticaly relative">
          <CentralHeroComponent size={450} />
          <TextComponent
            text="My name is Pablo Salgado and I have been working as a Full Stack Developer for the past 2 years. I have a strong passion for building modern and scalable web applications, and I have experience working with a variety of technologies and frameworks."
            top={241}
          />
        </div>

        <aside className="fixed right-0 mr-9 mt-9  z-10 bottom-0">
          <StickyContactComponent />
        </aside>
      </main>
    </div>
  );
}
