import Head from 'next/head';
import Image from 'next/image';
import CentralHeroComponent from '../components/central_hero_component/CentralHeroComponent';
import StickyContactComponent from '../components/sticky_contact_component/StickyContactComponent';
import useMousePosition from '../utils/hooks/useMousePosition';
export default function Home() {
  const mousePosition = useMousePosition();
  let angle = Math.atan2(mousePosition.y - 199, mousePosition.x - 472);
  return (
    <div>
      <Head>
        <title>Pablo Salgado Desarrollador Fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside className="fixed right-0 mr-9 mt-9" >
        <StickyContactComponent />
      </aside>
      <main className="flex h-screen justify-center items-center ">
        <CentralHeroComponent size={800} angle={angle} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
